# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/feiqian"
  weibo: "http://weibo.com/p/1005051672124647/home"
  zhihu: "http://www.zhihu.com/people/qianfei1992"
  douban: "http://www.douban.com/people/feiqian1992"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  #rss: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

baidu_analytics: true
# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://avatars1.githubusercontent.com/u/5433519?v=3&amp;s=460"
#是否开启分享
share: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: feiqian1992
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends: false


#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: A web developer fighting on the way.Hoping to share idea and experience with you here. 

